# Generated by Django 3.1.3 on 2021-08-14 18:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.CharField(blank=True, max_length=255)),
                ('name_of_organization', models.CharField(max_length=255)),
                ('organization', models.CharField(choices=[('Start-Up', 'Start-Up'), ('Club', 'Club'), ('Event', 'Event')], default='Start-Up', max_length=255)),
                ('logo', models.ImageField(upload_to='photos/')),
                ('website', models.CharField(blank=True, max_length=255, null=True)),
                ('area', models.CharField(blank=True, max_length=255, null=True)),
                ('visible', models.CharField(choices=[('Public', 'Public'), ('Private', 'Private')], default='Public', max_length=255)),
                ('description', models.TextField(null=True)),
                ('looking', models.TextField(null=True)),
                ('update', models.TextField(null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('interest', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.interest')),
            ],
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
