# Generated by Django 3.1.3 on 2021-08-22 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20210816_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='interest',
            field=models.CharField(choices=[('Environment', 'Environment'), ('STEM', 'STEM'), ('Reading/Writing', 'Reading/Writing'), ('Music/Art', 'Music/Art'), ('Other', 'Other')], default='Environment', max_length=255),
        ),
        migrations.DeleteModel(
            name='Interest',
        ),
    ]
