# Generated by Django 3.1.3 on 2021-08-14 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_post_recentlink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='recentphoto',
            field=models.ImageField(null=True, upload_to='events/'),
        ),
    ]
