# Generated by Django 3.1.3 on 2021-08-14 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210814_1744'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='recentphoto',
        ),
        migrations.AlterField(
            model_name='post',
            name='name_of_organization',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
