# Generated by Django 3.1.3 on 2021-08-16 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20210815_1610'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='recentlink',
        ),
    ]
