# Generated by Django 3.1.3 on 2021-08-16 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_remove_post_recentlink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='website',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
